version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  transfers-crud:
    build: .
    environment:
      PORT: 8000
      MONGO_URI: mongodb://localhost:27017/transfers-crud
      MONGO_OUTGOING_FILES_COLLECTION_NAME: outgoingFiles
      MONGO_INCOMING_FILES_COLLECTION_NAME: incomingFiles
      INCOMING_MAX_FILE_SIZE: 104857600

    ports:
      - 8000:8000
